#!/bin/bash

# OSX Rsync Backup (ORB)
#
# ORB is a RSync script for backup your entire osx disk/partition.
# You can also boot from your backup disk/partition (Very useful for test or restore functions).
#
# Created by: Rafael Biriba - biribarj@gmail.com
# More info: https://github.com/rafaelbiriba/ORB-osx-rsync-backup


# USAGE using source and destination edited in the file (below)
# $ ./orb

# USAGE using source and destination as parameter
# $ ./orb /Volumes/OSX /Volumes/BKP-Disk


# Edit the SOURCE (your current OSX Disk/Partition volume) and DESTINATION (your backup Disk/Partition volume)
SOURCE="/Volumes/BKP-RSYNC"
DESTINATION="/Volumes/BKP-TM"
# Or ignore these variables and use ORB inline parameters (and the variables below will be ignored). See github documentation for more info.


#############################################
######### Don't edit below this line ########
#### unless you know what you are doing #####
#############################################

SOURCE=${1:-$SOURCE}
DESTINATION=${2:-$DESTINATION}

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo -e "[ORB] Aborting the sync process: This script must be run as root\n"
   exit;
fi

if [ ! -r "$SOURCE" ]; then
    echo "[ORB] Aborting the sync process: Source $SOURCE not readable"
    exit;
fi

if [ ! -w "$DESTINATION" ]; then
    echo "[ORB] Aborting the sync process: Destination $DESTINATION not writeable"
    exit;
fi

rsync  --acls \
       --archive \
       --delete \
       --delete-excluded \
       --hard-links \
       --one-file-system \
       --sparse \
       --verbose \
       --xattrs \
       --times \
       --crtimes \
       --human-readable \
       --progress \
       --perms \
       --executability \
       --owner \
       --group  \
       --exclude '.Spotlight-*' \
       --exclude '.Trashes' \
       --exclude '/afs/*' \
       --exclude '/automount/*' \
       --exclude '/cores/*' \
       --exclude '/dev/*' \
       --exclude '/Network/*' \
       --exclude '/private/tmp/*' \
       --exclude '/private/var/run/*' \
       --exclude '/private/var/spool/postfix/*' \
       --exclude '/private/var/vm/*' \
       --exclude '/Previous Systems.localized' \
       --exclude '/tmp/*' \
       --exclude '/Volumes/*' \
       --exclude '*/.Trash' \
       "${SOURCE%/}" "${DESTINATION%/}"

bless --folder "${DESTINATION%/}"/System/Library/CoreServices

exit 0
