#!/bin/bash

# OSX Rsync Backup (ORB)
#
# ORB is a RSync script for backup your entire osx disk/partition.
# You can also boot from your backup disk/partition (Very useful for test or restore functions).
#
# Created by: Rafael Biriba - biribarj@gmail.com
# More info: https://github.com/rafaelbiriba/ORB-osx-rsync-backup

SOURCE="/Volumes/BKP-RSYNC/"

DESTINATION="/Volumes/BKP-TM/"


#############################################
######### Don't edit below this line ########
#### unless you know what you are doing #####
#############################################

SOURCE=${1:-$SOURCE}
DESTINATION=${2:-$DESTINATION}

# Ask for sudo password before continue
sudo -v

sudo rsync --acls \
           --archive \
           --delete \
           --delete-excluded \
           --hard-links \
           --one-file-system \
           --sparse \
           --verbose \
           --xattrs \
           --exclude '.Spotlight-*' \
           --exclude '.Trashes' \
           --exclude '/afs/*' \
           --exclude '/automount/*' \
           --exclude '/cores/*' \
           --exclude '/dev/*' \
           --exclude '/Network/*' \
           --exclude '/private/tmp/*' \
           --exclude '/private/var/run/*' \
           --exclude '/private/var/spool/postfix/*' \
           --exclude '/private/var/vm/*' \
           --exclude '/Previous Systems.localized' \
           --exclude '/tmp/*' \
           --exclude '/Volumes/*' \
           --exclude '*/.Trash' \
           "$SOURCE" "$DESTINATION"

exit 0
